Add macros
smh-my-head/charon pull request #1
Opened 2021-02-21 17:26 UTC by henryefranks

I've (finally!) got the macros working, and fully integrated with all your git trickery. I've tested both parts and assemblies and they work ok - assemblies seem to play less nice, but both diffs open the files in solidworks and from there you can compare manually. One requirement is that you have solidworks utilites enabled on startup (which I've added in an error message, but should probably be added to the README or something).

2021-02-21 21:45 UTC, tim-clifford commented
Awesome work. For some reason the part diff seems to be unreliable - it worked great the first time I tried it and now I can't get it to work again... it's extracting the right file paths but the compare function fails with return code 7009. Naturally all of the codes I could find docs for were in the range 0-8...

2021-02-21 21:46 UTC, tim-clifford commented
Also, it would be great if you could include .bas files (or any other non-binary format) for the macros, so that they can be version controlled :)

2021-02-21 22:01 UTC, tim-clifford requested changes
Just a couple minor things

2021-02-21 22:01 UTC, eleanor-clifford commented on sldasm_diff.sh
```suggestion

echo "Opening SolidWorks to diff $left_filename and $right_filename..."
echo "SolidWorks must exit fully before this diff can exit"
```
it would be nice to tell the user what's happening here because SolidWorks can be very slow to open and they might Ctrl-c or something :sweat_smile:

2021-02-21 22:01 UTC, eleanor-clifford commented on sldprt_diff.sh
```suggestion

echo "Opening SolidWorks to diff $left_filename and $right_filename..."
echo "SolidWorks must exit fully before this diff can exit"
```
same as the other comment

2021-02-21 22:01 UTC, eleanor-clifford commented on sldasm_diff.sh
> -rm diff_filename
lol there's a bug in my original code here, it's missing a `$` :sweat_smile:

2021-02-21 22:39 UTC, tim-clifford commented
It would be nice to have something like
```suggest
If longStatus <> gtSuccess Then
    ' I'm too scared to try splitting this line
    MsgBox "Comparison failed with exit code " + Str(longStatus) + ". Please open an issue at https://github.com/tim-clifford/sldworks-git-tools"
End If
```
in the macros to make this kind of problem easier to deal with in future.

2021-02-21 23:48 UTC, tim-clifford commented on sldasm_diff.sh
edited to match new commits in `master`

2021-02-21 23:49 UTC, tim-clifford commented on sldprt_diff.sh
edited to match new commits in `master`

2021-02-23 16:16 UTC, henryefranks commented
I've updated the macros and got that integrated with the new left/right filename stuff in master. When it comes to tracking the macro contents properly, I'm going to have to investigate a better solution than having a separate vba/bas file and swp file because otherwise every change would require manually editing both (as far as I can tell). I'll take a look into it and see what we can do.

2021-02-23 20:30 UTC, tim-clifford commented
I have dreams of a CI script that converts bas to swp... I don't think it's realistic though, SolidWorks' bullshit apparently extends to [forcing you to use their editor](https://www.codestack.net/solidworks-api/getting-started/macros/types)...? That's a new low, even for them.

I think for now we should just have both files, it sucks but it's better than having no idea what has changed... I'll write a little pre receive hook and pre commit hook which reject changes to one and not the other, to tide us over for now.

We will have to be careful merging any PRs that come in to make sure they have no malicious changes though :(

2021-02-23 22:13 UTC, tim-clifford commented on macros/compareprt.swb
> +    Dim longStatus     As Long
I like aligning like this, it's very aesthetically pleasing :ok_hand: btw, i have some auto-aligning vimscript if you want it

2021-02-23 22:13 UTC, tim-clifford commented on macros/compareasm.swb
> +' COPYRIGHT (C) 2021 HENRY FRANKS
```suggestion
' COMPARE SOLIDWORKS ASSEMBLIES
' COPYRIGHT (C) 2021 HENRY FRANKS
' vi: ft=basic
```
vim gang

2021-02-23 22:13 UTC, tim-clifford commented on macros/compareprt.swb
> +                   + "https://github.com/tim-clifford/sldworks-git-tools"
Damn, impressed you figured out splitting across lines

2021-02-23 22:13 UTC, tim-clifford commented on macros/compareprt.swb
> +' COPYRIGHT (C) 2021 HENRY FRANKS
```suggestion
' COMPARE SOLIDWORKS ASSEMBLIES
' COPYRIGHT (C) 2021 HENRY FRANKS
' vi: ft=basic
```
vim gang

2021-02-23 22:34 UTC, tim-clifford commented on macros/compareasm.swb
> +    End If
Is it possible for `CompareGeometry` to fail but `Close` to succeed? Should we duplicate the exit code check between each call?

2021-02-23 22:35 UTC, tim-clifford commented on macros/compareasm.swb
> +    End If
ugh selected too many lines and can't change it

2021-02-23 23:05 UTC, tim-clifford approved these changes

2021-02-23 23:06 UTC, merged